[global.databases]
postgres = { url = "postgres://postgres:password@localhost/beidanci", pool_size = 20 }

[development]
address = "127.0.0.10"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
zoho_smtp_app_username = "demo@example.com"
zoho_smtp_app_password = "demo"
secret_key = "iVIEB5M1/yNH5meXzdM1eOF1uDY6fX/t1pda1FhllRE="

[staging]
address = "0.0.0.0"
port = 8000
workers = 10
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
zoho_smtp_app_username = "demo@example.com"
zoho_smtp_app_password = "demo"
secret_key = "iVIEB5M1/yNH5meXzdM1eOF1uDY6fX/t1pda1FhllRE="

[production]
address = "127.0.0.3"
port = 8000
workers = 2
keep_alive = 5
log = "critical"
limits = { forms = 32768 }
