-- Your SQL goes here
CREATE TABLE users(
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE vocabs (
  vocab VARCHAR PRIMARY KEY NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE vocabs IS '不重复的且唯一的单词列表,也是其他关联表格的主键';

CREATE TABLE vocab_dicts(
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
  vocab VARCHAR NOT NULL REFERENCES vocabs,
  partofspeech VARCHAR NOT NULL,
  meaning VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE vocab_books (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE vocab_book_contents (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
  book_id UUID NOT NULL REFERENCES vocab_books(id),
  vocab VARCHAR NOT NULL REFERENCES vocabs,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE vocab_speeches (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  vocab VARCHAR NOT NULL REFERENCES vocabs,
  mp3 BYTEA NOT NULL
);
